cooccur = [
{text: 'students:gunviolence', size: '341'},
{text: 'nra:gunviolence', size: '335'},
{text: 'gunviolence:america', size: '164'},
{text: 'violence:gunviolence', size: '90'},
{text: 'people:gunviolence', size: '72'},
{text: 'people:killed', size: '48'},
{text: 'violence:people', size: '45'},
{text: 'killed:gunviolence', size: '41'},
{text: 'people:america', size: '19'},
{text: 'violence:america', size: '9'},
{text: 'violence:killed', size: '8'},
{text: 'violence:nra', size: '4'},
{text: 'people:nra', size: '4'},
{text: 'students:people', size: '3'},
{text: 'violence:students', size: '2'},
{text: 'nra:america', size: '2'},
{text: 'students:america', size: '1'},
{text: 'parklandschoolshooting:gunviolence', size: '1'},
{text: 'mother:gunviolence', size: '1'},
{text: 'killed:america', size: '1'}
];